### ISSUE TITLE
Hovering shifts other components

### ISSUE THREAD

**Issue by Sam-Varghese** [GDSC-MPSTME-Shirpur/GDSC-MPSTME-Website#12]
First and foremost, the website is awesome! looks great. Thanks for making such an amazing website for GDSC NMIMS Shirpur.

Just a thing I noticed, whenever I hover over some icons, then **other components also start to shift slightly** which doesn't look nice. Here's a video that explains the issue better:

![Issue](https://user-images.githubusercontent.com/79152648/145713044-f467d7d5-d15a-4311-a983-0b1116ca5a90.gif)

Regards
Sam Varghese
GDSC PR Core Team

**Comment by Sam-Varghese** [comment]
I've found a fix to this issue and submitted it in #13  Here's a gif of the final website
![issueSol](https://user-images.githubusercontent.com/79152648/145719183-01d3adfe-384c-43b6-99a6-4b9be31f792a.gif)

**Comment by GDSC-MPSTME-Shirpur** [comment]
Great work Sam your work is really appreciable.. Thanks
