### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Sam-Varghese** [GDSC-MPSTME-Shirpur/GDSC-MPSTME-Website#17]
There's a typo at https://gdsc-mpstme-shirpur.web.app/events `30 days of the Google cloud` section, which I'd like to bring to your notice

![image](https://user-images.githubusercontent.com/79152648/173236055-41f49b59-4f64-4cf2-8ffd-28a25f6e4275.png)

Google has been misspelled as `Goolge`, which I've highlighted in the above screenshot.

Regards
Sam Varghese

**Comment by Sam-Varghese** [comment]
Here's the line that needs to be corrected: https://github.com/GDSC-MPSTME-Shirpur/GDSC-MPSTME-Website/blob/f23dbe76695e7b2a9fa6b6fba2aea02d3a12a07d/src/Components/Events.js#L11

**Comment by GDSC-MPSTME-Shirpur** [comment]
Hello Sam, Thanks for raising this issue, we have taken care of it and made the necessary updates. Thanks :)
